"""Publishes the corpus for the frontend.

The web app is a reader, not a producer. It never runs PARI, never verifies
anything, and never touches the working tree: it loads a folder of static
files and displays what they say. This script is the only bridge, and it
does three things and no more.

It copies each bundle across untouched, byte for byte, so the digest shown
in the browser is the digest of the file itself and not of some repackaged
version of it. It writes an index listing what is available. And it
converts the policies from YAML to JSON, because a browser has no YAML
parser and shipping one to read four criteria would be silly.

Nothing here computes a verdict. The frontend applies policies itself, from
the same declarative criteria the Python engine reads, which means the two
implementations can be compared against each other.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from core.bundle import canonical
from core.bundle.model import Bundle
from core.policy.engine import available_policies, load_policy

ROOT = Path(__file__).resolve().parents[1]


def export(corpus: Path, out: Path) -> int:
    bundles = sorted(corpus.glob("*.ccert"))
    if not bundles:
        print(f"no bundles in {corpus}; run tools\\corpus.bat first", file=sys.stderr)
        return 2

    out.mkdir(parents=True, exist_ok=True)
    index = []

    for path in bundles:
        raw = path.read_bytes()
        document = json.loads(raw.decode("utf-8"))
        bundle = Bundle.from_obj(document)
        bundle.validate()

        # Copy verbatim. Re-serialising would risk showing a digest the file
        # does not actually have.
        shutil.copyfile(path, out / path.name)

        subject = bundle.subject
        index.append(
            {
                "file": path.name,
                "label": subject.get("label", path.stem),
                "source": subject.get("source", ""),
                "bits": canonical.as_int(subject["field"]["p"]).bit_length(),
                "digest": canonical.digest_bytes(raw.rstrip(b"\n")),
                "claims": len(bundle.claims),
                "tiers": bundle.tier_counts(),
            }
        )

    policies = []
    for name in available_policies():
        policy = load_policy(name)
        policies.append(
            {
                "name": policy.name,
                "title": policy.title,
                "source": " ".join(policy.source.split()),
                "accept_tiers": list(policy.accept_tiers),
                "criteria": [asdict(criterion) for criterion in policy.criteria],
            }
        )

    payload = {"bundles": index, "policies": policies}
    (out / "index.json").write_text(
        json.dumps(payload, indent=1, ensure_ascii=False),
        encoding="utf-8",
        newline="\n",
    )

    # The same data as a module. A page that imports its corpus instead of
    # fetching it can be opened straight off the disk, with no server and no
    # install, which is the difference between a tool people try and a tool
    # people read about.
    documents = {}
    for entry in index:
        raw = (out / entry["file"]).read_text(encoding="utf-8")
        documents[entry["file"]] = json.loads(raw)

    module = (
        "// Generated by tools/export_web.py. Do not edit.\n"
        "// The corpus, inlined so the page needs no server.\n\n"
        f"export const index = {json.dumps(payload, ensure_ascii=False)};\n\n"
        f"export const documents = {json.dumps(documents, ensure_ascii=False)};\n"
    )
    generated = ROOT / "web" / "src" / "corpus.generated.js"
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(module, encoding="utf-8", newline="\n")

    print(f"exported {len(index)} bundle(s) and {len(policies)} policies to {out}")
    print(f"inlined the same corpus into {generated.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Publish the corpus for the web app.")
    parser.add_argument("--corpus", default=str(ROOT / "corpus"))
    parser.add_argument("--out", default=str(ROOT / "web" / "public" / "data"))
    args = parser.parse_args()
    return export(Path(args.corpus), Path(args.out))


if __name__ == "__main__":
    raise SystemExit(main())
