"""Turns the compiled module into something a single-file page can hold.

    python tools\\inline_wasm.py

`wasm-bindgen --target web` emits a `.js` shim that fetches a `.wasm`
alongside it. That is the right arrangement for a served page and the
wrong one here: this page is opened from `file://`, and a fetch from
`file://` is refused by every browser worth the name. It is also the
wrong arrangement for what the release is meant to be — one file, handed
to someone, that works.

So the module is embedded as base64 and the shim is rewritten to decode
it rather than fetch it. The cost is about a third in size on top of the
module itself; the page goes from roughly 370 KB to something over a
megabyte. That is the price of "open this file and check for yourself"
remaining literally true, and it is worth paying.

The generated file is deliberately not hand-edited afterwards. It is
regenerated whenever the verifier changes, and a hand edit would be lost
without warning — which is why this writes a header saying so.
"""

from __future__ import annotations

import base64
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.wasm_stamp import PREFIX, stamp

ROOT = Path(__file__).resolve().parent.parent
WASM_DIR = ROOT / "web" / "src" / "wasm"
MODULE = WASM_DIR / "ccert_bg.wasm"
SHIM = WASM_DIR / "ccert.js"
OUT = ROOT / "web" / "src" / "verifier.generated.js"


def main() -> int:
    if not MODULE.is_file() or not SHIM.is_file():
        print(
            "no wasm build found; run tools\\build_wasm.bat first",
            file=sys.stderr,
        )
        return 1

    raw = MODULE.read_bytes()
    encoded = base64.b64encode(raw).decode("ascii")
    shim = SHIM.read_text(encoding="utf-8")

    # The shim's default export takes a module source. Given bytes it
    # skips the fetch entirely, which is the whole trick — no rewriting of
    # its internals, just a different argument.
    body = f'''// Generated by tools/inline_wasm.py. Do not edit.
//
// The verifier, compiled to wasm and embedded here as base64 so the page
// stays a single file. A `.wasm` beside the page would be fetched, and a
// fetch from file:// is refused by every browser — which is exactly how
// this release is meant to be opened.
//
// Regenerated whenever the verifier changes. Anything written here by
// hand disappears the next time.

import init, {{ verify_certificate, verifier_version }} from "./wasm/ccert.js";

const ENCODED = "{encoded}";

function bytes() {{
  const binary = atob(ENCODED);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
  return out;
}}

let ready = null;

/** Load the module once, and hand the same promise to every later caller. */
export function load() {{
  if (ready === null) ready = init({{ module_or_path: bytes() }});
  return ready;
}}

/**
 * Verify a certificate's text, in this page, and return the verdict.
 *
 * The same JSON `ccert-verify --json` prints, from the same code. If this
 * ever disagrees with the command line, one of them is wrong and the
 * disagreement is the finding.
 */
export async function verify(name, text) {{
  await load();
  return JSON.parse(verify_certificate(name, text));
}}

export async function version() {{
  await load();
  return verifier_version();
}}

export const SIZE_BYTES = {len(raw)};
'''
    # The stamp goes in first, so `make_release.py` can refuse a page
    # whose verifier predates the tree. Without it a release can ship a
    # browser module older than the certificates beside it, and the
    # symptom is a valid certificate refused in the page and accepted on
    # the command line — which reads as a broken certificate.
    OUT.write_text(f"{PREFIX}{stamp()}\n" + body, encoding="utf-8")
    print(
        f"inlined {len(raw) / 1024:.0f} KB of wasm "
        f"({len(encoded) / 1024:.0f} KB as base64) into {OUT.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
